import{a as v,S,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const E="49365626-6bf9b0bb5948f971197bdaec6",P="https://pixabay.com/api/",R=15;async function f(o,r){try{return(await v.get(P,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:r}})).data}catch(t){throw console.error("Error fetching images:",t),t}}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more");let q=new S(".gallery a");function h(){m.classList.add("visible")}function y(){m.classList.remove("visible")}function O(){p.innerHTML=""}function L(o){if(o.length===0){n.error({title:"Oops!",message:"Sorry, no images found. Try again!",position:"topRight"});return}const r=o.map(t=>`
        <a href="${t.largeImageURL}" class="gallery-item">
            <img src="${t.webformatURL}" alt="${t.tags}" />
            <div class="info">
                <p>Likes: ${t.likes}</p>
                <p>Views: ${t.views}</p>
                <p>Comments: ${t.comments}</p>
                <p>Downloads: ${t.downloads}</p>
            </div>
        </a>
    `).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function b(){g.classList.add("visible")}function l(){g.classList.remove("visible")}const u=document.querySelector(".search-form"),$=u.querySelector("input[name='searchQuery']"),M=document.querySelector(".load-more");let a="",i=1;const w=15;u.addEventListener("submit",async o=>{if(o.preventDefault(),a=$.value.trim(),a===""){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}i=1,O(),l(),h();try{const r=await f(a,i);if(r.hits.length===0){n.error({title:"Oops!",message:"Sorry, no images found. Try again!",position:"topRight"});return}L(r.hits),r.totalHits>w&&b()}catch{n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}u.reset()});M.addEventListener("click",async()=>{i+=1,h(),l();try{const o=await f(a,i);L(o.hits),i*w>=o.totalHits?(l(),n.info({title:"End of results",message:"You've reached the end of search results.",position:"topRight"})):b()}catch{n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
