import{a as S,S as v,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const E="49365626-6bf9b0bb5948f971197bdaec6",q="https://pixabay.com/api/",M=15;async function f(e,o){try{return(await S.get(q,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:o}})).data}catch(r){throw console.error("Error fetching images:",r),r}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more");let P=new v(".gallery a");function y(){g.classList.add("visible")}function h(){g.classList.remove("visible")}function R(){p.innerHTML=""}function L(e){if(e.length===0){n.error({title:"Oops!",message:"Sorry, no images found. Try again!",position:"topRight"});return}const o=e.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" />
            <div class="info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        </a>
    `).join("");p.insertAdjacentHTML("beforeend",o),P.refresh()}function w(){m.classList.add("visible")}function l(){m.classList.remove("visible")}function O(){const e=document.querySelector(".end-message");e&&(e.style.display="block")}function B(){const e=document.querySelector(".end-message");e&&(e.style.display="none")}const d=document.querySelector(".search-form"),$=d.querySelector("input[name='searchQuery']"),A=document.querySelector(".load-more");document.querySelector(".end-message");let a="",i=1;const b=15;d.addEventListener("submit",async e=>{if(e.preventDefault(),a=$.value.trim(),a===""){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}i=1,R(),l(),B(),y();try{const o=await f(a,i);if(o.hits.length===0){n.error({title:"Oops!",message:"Sorry, no images found. Try again!",position:"topRight"});return}L(o.hits),o.totalHits>b&&w()}catch{n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{h()}d.reset()});A.addEventListener("click",async()=>{i+=1,y(),l();try{const e=await f(a,i);L(e.hits),i*b>=e.totalHits?(l(),O(),n.info({title:"End of results",message:"You've reached the end of search results.",position:"topRight"})):w()}catch{n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"})}finally{h()}});function H(){const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}document.addEventListener("DOMContentLoaded",()=>{H()});
//# sourceMappingURL=index.js.map
