import{a as E,S,i as p}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&f(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function f(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const v="49365626-6bf9b0bb5948f971197bdaec6",q="https://pixabay.com/api/",B=15;async function y(t,o=1){try{return(await E.get(q,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:o}})).data}catch(r){throw console.error("Error fetching images:",r),r}}const d=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let M=new S(".gallery a");function g(){m.style.display="block"}function b(){m.style.display="none"}function O(){d.innerHTML=""}function L(t){if(t.length===0){p.error({title:"Oops!",message:"Sorry, no images found. Try again!",position:"topRight"});return}const o=t.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" />
            <div class="info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        </a>
    `).join("");d.insertAdjacentHTML("beforeend",o),M.refresh()}function w(){h.style.display="block"}function c(){h.style.display="none"}function R(){p.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function $(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const l=document.querySelector(".form"),I=l.querySelector("input[name='search-text']"),P=document.querySelector(".load-more");let a="",s=1,u=0;l.addEventListener("submit",async t=>{if(t.preventDefault(),a=I.value.trim(),a!==""){s=1,O(),c(),g();try{const o=await y(a,s);if(u=o.totalHits,o.hits.length===0)return;L(o.hits),u>15&&w()}catch(o){console.error("Search error:",o)}finally{b()}l.reset()}});P.addEventListener("click",async()=>{s++,g(),c();try{const t=await y(a,s);L(t.hits),$(),s*15>=u?(c(),R()):w()}catch(t){console.error("Error loading more images:",t)}finally{b()}});
//# sourceMappingURL=index.js.map
